### ISSUE TITLE
yo --- aware of mullen's gender package right?

### ISSUE THREAD

**Issue by soodoku** [mkearney/name2sex#1]
why is this diff.?

https://github.com/ropensci/gender

**Comment by mkearney** [comment]
Was aware. I actually just wanted a simplified version of it for my own purposes (I'm working with a grad student so in addition to simplicity I also wanted to be able to control and be consistent with however we decide to parse the first names out of a string). 

So if anyone finds their way here, I'd encourage you to use https://github.com/ropensci/gender instead. We made some decisions when making this package that are probably not completely obvious---it'll be more transparent to use https://github.com/ropensci/genderdata and https://github.com/ropensci/gender directly!

**Comment by soodoku** [comment]
Got it man. Thanks for engaging. Just wanted to check if I was missing
something. Thanks.

**Comment by mkearney** [comment]
Thanks for creating the issue! I'm not always the best about checking for duplicate packages, and it's a good reminder that I should probably add a note to the README as well!
